export const RPC_URL = "https://bsc-testnet.public.blastapi.io";
export const OVL_CONTRACT_ADDRESS = "0xb880E767739A82Eb716780BDfdbC1eD7b23BDB38"
export const COLLATERAL_AMOUNT_OVL = "1";
export const LEVERAGE = 1;
export const SLIPPAGE_PERCENT = 1; 
export const MIN_UNWIND_DELAY_MINUTES = 5;
export const MAX_UNWIND_DELAY_MINUTES = 15;
export const DELAY_BETWEEN_RUNS_MS = 60 * 1000;
export const WALLET_NAME = "wallet";
